export enum cryptoTypes { 
  FETCH_CRYPTO_DATA_REQUEST = "FETCH_CRYPTO_DATA_REQUEST",
  FETCH_CRYPTO_DATA_SUCCESS = "FETCH_CRYPTO_DATA_SUCCESS",
  FETCH_CRYPTO_DATA_FAILURE = "FETCH_CRYPTO_DATA_FAILURE",
  FETCHED_CRYPTO_DATA_SUCCESS = "FETCHED_CRYPTO_DATA_SUCCESS",
  START_CRYPTO_DATA_LOADING = "START_CRYPTO_DATA_LOADING",
  END_CRYPTO_DATA_LOADING = "END_CRYPTO_DATA_LOADING",
  SET_WATCHLIST_DATA_SUCCESS = "SET_WATCHLIST_DATA_SUCCESS",

}